language: android
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

before_script:
    - chmod +x gradlew

#Build, and run tests
script:
  - ./gradlew assembleDebug -PdisablePreDex
  - ./gradlew assembleAndroidTest -PdisablePreDex
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &amp;
  - adb install -r app/build/outputs/apk/app-mock-debug.apk
  - adb install -r app/build/outputs/apk/app-mock-debug-androidTest-unaligned.apk
  - ./gradlew check -PdisablePreDex --continue --stacktrace
  - .buildscript/launchInstrumentationTests.sh

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
env:
  - GRADLE_OPTS="-XX:MaxPermSize=1024m -XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m"
